# Generated by Django 3.2 on 2022-10-13 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default=uuid.uuid4, max_length=36)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
    ]
